### PR TITLE
Ensure property order for NotificationOrderExt models

### PR DESCRIPTION
**Pull request by acn-sbuad**
## Description

Base properties such as id and creator now appear before model specific properties such as processing status or email template

### CODE REVIEW

**Comment by SandGrainOne** [comment]
Are any of these models included in the order request and will this force clients to list properties in a specific order?

**Review by tba76 — APPROVED** [review]
Nice 🍺

**Comment by acn-sbuad** [comment]
> Are any of these models included in the order request and will this force clients to list properties in a specific order?

@SandGrainOne  Order request has seperate models. Either way jsonPropertyOrder only affect serialization and not deserialization.

**Comment by acn-sbuad** [comment]
Property order verified in AT22
```
{
  "id": "59b1d86d-fe39-44e5-b47f-f4677e610f32",
  "requestedSendTime": "2024-05-30T12:45:25.546319Z",
  "creator": "ttd",
  "created": "2024-05-30T12:45:25.5470899Z",
  "notificationChannel": "Email",
  "resourceId": "app_ttd_apps-test",
  "recipients": [
    {
      "organizationNumber": "313009955"
    }
  ],
  "emailTemplate": {
    "fromAddress": "noreply@altinn.cloud",
    "subject": "A test email from Altinn Notifications",
    "body": "Test email",
    "contentType": "Plain"
  },
  "links": {
    "self": "https://platform.at22.altinn.cloud/notifications/api/v1/orders/59b1d86d-fe39-44e5-b47f-f4677e610f32",
    "status": "https://platform.at22.altinn.cloud/notifications/api/v1/orders/59b1d86d-fe39-44e5-b47f-f4677e610f32/status"
  }
}
```

**Pull request merged**
